"""``numbers.json`` — the claim-tracing registry.

Implements the reproducibility contract of ROADMAP.md §4.4 and referee check **R-5**.

Every numerical value that appears in the manuscript is written as ``\\jnum{key}`` and
resolves against this registry.  A numeral typed literally into a results sentence is a
delivery-blocking defect, because it cannot be traced back to a recorded run.  Each entry
carries its value, unit, display precision, the experiment that produced it and the git
commit the code was at, so a reader can find the run that made it.
"""

from __future__ import annotations

import json
import subprocess
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True, slots=True)
class Entry:
    """One traceable number."""

    value: float | int | str
    unit: str
    precision: int
    source: str
    git_sha: str


def git_sha() -> str:
    """Short commit hash, or ``"unknown"`` outside a repository."""
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        return out.stdout.strip()
    except Exception:  # pragma: no cover - environment dependent
        return "unknown"


class Registry:
    """Accumulates entries and writes ``numbers.json``."""

    def __init__(self, path: Path) -> None:
        self.path = Path(path)
        self.entries: dict[str, Entry] = {}
        self._sha = git_sha()

    def add(
        self,
        key: str,
        value: float | int | str,
        unit: str = "",
        precision: int = 2,
        source: str = "",
    ) -> None:
        if key in self.entries:
            raise KeyError(f"duplicate registry key: {key}")
        self.entries[key] = Entry(
            value=value,
            unit=unit,
            precision=precision,
            source=source,
            git_sha=self._sha,
        )

    def set(self, key: str, value: float | int | str, **kwargs: Any) -> None:
        """Add or overwrite (used when a runner is re-executed in one session)."""
        self.entries.pop(key, None)
        self.add(key, value, **kwargs)

    def write(self) -> Path:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        payload = {k: asdict(v) for k, v in sorted(self.entries.items())}
        self.path.write_text(json.dumps(payload, indent=2))
        return self.path

    def write_latex_macros(self, path: Path) -> Path:
        r"""Emit ``\jnum`` definitions so LaTeX can resolve keys without a build step.

        The manuscript writes ``\jnum{e3.core.empty.rate}``; this file defines each key so
        that a stale key becomes a *compile* error rather than a plausible-looking wrong
        number.
        """
        path.parent.mkdir(parents=True, exist_ok=True)
        lines = [
            "% Generated by jsspt_tou.analysis.registry -- do not edit by hand.",
            r"\makeatletter",
            r"\newcommand{\jnum}[1]{\@ifundefined{jnum@#1}{\textbf{??#1??}}{\csname jnum@#1\endcsname}}",
            r"\makeatother",
        ]
        for key, entry in sorted(self.entries.items()):
            if isinstance(entry.value, str):
                text = entry.value
            elif isinstance(entry.value, int):
                text = str(entry.value)
            else:
                text = f"{entry.value:.{entry.precision}f}"
            safe = key.replace("_", "@")
            lines.append(rf"\expandafter\def\csname jnum@{key}\endcsname{{{text}}}")
        path.write_text("\n".join(lines) + "\n")
        return path

    @staticmethod
    def load(path: Path) -> dict[str, Entry]:
        raw = json.loads(Path(path).read_text())
        return {k: Entry(**v) for k, v in raw.items()}
